version: '3.4'

services:
  messagebroker:
    image: rabbitmq:management-alpine

  contacts.api:
    image: ${DOCKER_REGISTRY-}contactsapi
    build:
      context: .
      dockerfile: src/Services/Contacts/Contacts.API/Dockerfile
